name: Generate db models


on:
  push:
    branches: [ main, unstable ]
  pull_request:
    branches: [ main, unstable ]
    paths:
     - create_db_models.sh
     - sqlboiler.toml
     - 'tools/schema_converter/*'
     - 'schema/*'


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Set up databases
      run:  |
        # Convert schemas
         go run ./tools/schema_converter
         

        # Install/start databases
        sudo systemctl start postgresql.service
        sudo systemctl start mysql.service
        sudo docker pull mcr.microsoft.com/mssql/server:2019-latest
        
        sudo docker run -e "ACCEPT_EULA=Y" -e 'SA_PASSWORD=jdksjds6dsads8a97d!' \
        -p 1433:1433 --name sql1 --hostname sql1 \
        -d mcr.microsoft.com/mssql/server:2019-latest
        
        sleep 5
        
        # Import schema
        sqlcmd -H sql1 -U SA -P 'jdksjds6dsads8a97d!' -Q "CREATE DATABASE bntp_test"    
        sqlcmd -H sql1 -U SA -P 'jdksjds6dsads8a97d!' -d bntp_test -i "schema/bntp_sqlserver.sql"
        
        mysql -u root -proot -e "CREATE DATABASE bntp_test"
        mysql -u root -proot -D bntp_test < schema/bntp_mysql.sql
         
        sudo -u postgres psql -c 'create database bntp_test;'
        sudo -u postgres psql -d bntp_test -a -f schema/bntp_postgres.sql
        sudo sed -i 's/peer/trust/g' $(sudo -u postgres psql -c 'show hba_file' 2> /dev/null | grep pg_hba)
        sudo sed -i 's/scram-sha-256/trust/g' $(sudo -u postgres psql -c 'show hba_file' 2> /dev/null | grep pg_hba)
        # sudo cat $(sudo -u postgres psql -c 'show hba_file' 2> /dev/null | grep pg_hba)
        sudo systemctl restart postgresql.service
        
        sqlite3 bntp_test.db < schema/bntp_sqlite.sql
        
    - name: Update SQLboiler models
      run: ./create_db_models.sh
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: ./models/* ./schema/*
