name: Go

on:
  push:
    branches: [ main, unstable ]
  pull_request:
    branches: [ main, unstable ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Update test DB
      run:  |
        sudo apt-get install -y sqlite3
        rm test/data/bntp_test.db 
        sqlite3 test/data/bntp_test.db < bntp.sql

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
