name: Go

on:
  push:
    branches: [ main, unstable ]
  pull_request:
    branches: [ main, unstable ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Set up databases
      run:  |
        sudo systemctl start postgresql.service
        sudo systemctl start mysql.service
        sudo docker pull mcr.microsoft.com/mssql/server:2019-latest
        
        sudo docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=jdksjds6dsads8a97d!" \
        -p 1433:1433 --name sql1 --hostname sql1 \
        -d mcr.microsoft.com/mssql/server:2019-latest
        
        sqlcmd -S localhost,1433 -U SA -P "jdksjds6dsads8a97d!" -q "CREATE DATABASE bntp_test"    
        sqlcmd -S localhost,1433 -U SA -P "jdksjds6dsads8a97d!" -d bntp_test -i "schema/bntp_sqlserver.sql"
        
        mysql -u root -proot -e "CREATE DATABASE bntp_test"
        mysql -u root -proot -D bntp_test < schema/bntp_mysql.sql
         
        sudo -u postgres psql -c 'create database bntp_test;'
        sudo -u postgres psql -d bntp_test -a -f schema/bntp_postgres.sql
        
        sqlite3 bntp_test.db < bntp.sql
        
    - name: Update SQLboiler
      run:  ./create_db_models.sh
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: ./models/*

    - name: Build
      run: |
        cp bntp.sql test/bntp.sql
        go build -v ./...


    - name: Test
      run: go test -coverprofile coverage.out -v ./...

    - name: Report coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.out
