name: Go

on:
  push:
    branches: [ main, unstable ]
  pull_request:
    branches: [ main, unstable ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Update SQLboiler
      run:  |
        sqlite3 bntp_test.db < bntp.sql
        sqlboiler --add-soft-deletes --wipe sqlite3
        ls -1 ./models | xargs sed -i 's/t.Parallel()//'
        go test -v ./models
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: ./models/*

    - name: Build
      run: |
        cp bntp.sql test/bntp.sql
        go build -v ./...


    - name: Test
      run: go test -coverprofile coverage.out -v ./...

    - name: Report coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.out
