name: Go tests

on:
  push:
    branches: [ main, unstable ]
  pull_request:
    branches: [ main, unstable ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: |
        cp schema/bntp_sqlite.sql test/bntp.sql
        go build -v ./...
        mkdir -p /home/runner/.config/bntp/
        touch /home/runner/.config/bntp/bntp.log
        
        # Lazy workaround for ci env <-> dev env inconsistency
        mkdir -p /home/runner/work/bntp.go/schema/
        cp schema/bntp_sqlite.sql /home/runner/work/bntp.go/schema/bntp_sqlite.sql


    - name: Test
      # run: go test -coverprofile coverage.out -v -coverpkg ./... ./...
      run: go test -coverprofile coverage.out -v -coverpkg ./... ./cmd/...

    - name: Report coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.out
