name: Go

on:
  push:
    branches: [ main, unstable ]
  pull_request:
    branches: [ main, unstable ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: |
        cp schema/bntp_sqlite.sql test/bntp.sql
        go build -v ./...


    - name: Test
      run: go test -coverprofile coverage.out -v ./...

    - name: Report coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.out
