// Code generated by SQLBoiler 4.10.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("BookmarkTypes", testBookmarkTypesUpsert)

	t.Run("Bookmarks", testBookmarksUpsert)

	t.Run("DocumentTypes", testDocumentTypesUpsert)

	t.Run("Documents", testDocumentsUpsert)

	t.Run("Tags", testTagsUpsert)
}
